#!/usr/bin/env python
# coding: utf-8

# In[1]:


print('Hello')

# In[2]:


import warnings

warnings.filterwarnings("ignore")
import pandas as pd
from pandas.tseries.offsets import BDay, Day
import datetime


class custom_today:

    def today(backday=0):
        today = pd.datetime.today()
        what_date1 = today + Day(backday)
        what_date1 = format(what_date1, '%Y%m%d')
        print(type(what_date1))
        today = what_date1
        return today

    def get_ddd():
        ddd = datetime.datetime.today().weekday()
        ddds = ['Mon', "Tues", 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        print(f' Today is : {ddd}, {ddds[ddd]}')
        return ddd


# In[3]:


if (custom_today.get_ddd() == 0):  # ddd 월요일
    back2today = -3
elif (custom_today.get_ddd() == 6):  # ddd 월요일 인데  일요일로 ['미쿸']
    back2today = -2
else:
    back2today = -1  # 화수목금토일

print(f"======= The reference Date is :  {custom_today.today(back2today)} ======= ")

# In[4]:


### from henrryQuant
### 1. otp 만들어주세요  request

import requests
import pandas as pd
from io import BytesIO

gen_otp_url = 'http://data.krx.co.kr/comm/fileDn/GenerateOTP/generate.cmd'

gen_otp_data = {
    'tboxindIdx_finder_equidx0_1': '코스피 200',
    'indIdx': '1',
    'indIdx2': '028',
    'codeNmindIdx_finder_equidx0_1': '코스피 200',
    'param1indIdx_finder_equidx0_1': '',
    'trdDd': f'{custom_today.today(back2today)}',
    'money': '1',
    'csvxls_isNo': 'false',
    'name': 'fileDown',
    'url': 'dbms/MDC/STAT/standard/MDCSTAT00601',
}

headers = {
    'Referer': 'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36'
    # generate.cmd에서 찾아서 입력하세요
}

r = requests.get(gen_otp_url, gen_otp_data, headers=headers)


# In[5]:


### 2. otp 제출하고  data 받기
gen_req_url = 'http://data.krx.co.kr/comm/fileDn/download_excel/download.cmd'

form_data = {
    'code': r.content
}

headers = {
    'Referer': 'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201010105',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36'
    # generate.cmd에서 찾아서 입력하세요
}

## 2. OTP 를 제출 하고  data  받기
r = requests.post(gen_req_url, form_data, headers=headers)
df = pd.read_excel(BytesIO(r.content))


# In[6]:


df['종목코드'] = df['종목코드'].astype(str)


# In[7]:


df['종목코드'] = df['종목코드'].str.zfill(6)


# In[8]:


df.drop_duplicates(subset=['종목코드'])
print(df)

# In[10]:


df.to_excel('C:\\URLPATH\\bm.xlsx')


from tqdm import tqdm
import time
for k in tqdm(range(0,10)):
    #print(f"============== {k}/10 ==== ")
    time.sleep(1)
# In[ ]:


